name: Download GoFile Every 21 Hours

on:
  schedule:
    - cron: "0 */21 * * *"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Download file from GoFile
        run: |
         pip install -r requirements.txt
         gofile-downloader.py https://gofile.io/d/ifad83
      - name: Save to GitHub
        if: always()
        run: |
          git pull
          git config user.name github-actions
          git config user.email actions@github.com
          git add ./woke
          git commit -m "revived"
          git push
